### ISSUE TITLE
Infinite Loop 'Increasing the capacity violation limit in Split'

### ISSUE THREAD

**Issue by uwwint** [vidalt/HGS-CARP#1]
Solving the attached CARP yields an infinite loop.

./gencarp test.txt -type 30 -t 1200

Increasing the capacity violation limit in Split
Increasing the capacity violation limit in Split
Increasing the capacity violation limit in Split
Increasing the capacity violation limit in Split
.....

[test.txt](https://github.com/vidalt/HGS-CARP/files/5160728/test.txt)

**Comment by uwwint** [comment]
Found out, this is due to the graph not being connected.

**Comment by vidalt** [comment]
Yes, my apologies for the unclear error message. This is a classic behavior when it's impossible to "Split" a given giant tour. In theory, given that capacity and duration constraints are relaxed and penalized, it should always be possible to Split. The most common cause for this message is when there is an issue in the data, for example, disconnected graphs, mistakes when parsing some essential information such as vehicle capacity, etc...
